"""Generate cross-language test vectors from tools/hudmath.py.

Writes:
    tests/vectors.json               (read by tests/test_hud_math.js)
    firmware/test_host/vectors.h     (compiled into the C host tests)
"""
import json
import os
import random
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
import hudmath as hm  # noqa: E402

random.seed(1724)
OBS = [
    (36.5967, -121.8750, 20.0),   # Monterey
    (-33.8688, 151.2093, 50.0),   # Sydney (southern/eastern hemisphere)
    (64.1466, -21.9426, 10.0),    # Reykjavik (high latitude)
    (0.0, 0.0, 0.0),
]

cases = []
cfg = hm.ProjCfg()
for obs in OBS:
    for _ in range(12):
        e = random.uniform(-3000, 3000)
        n = random.uniform(-3000, 3000)
        u = random.uniform(-100, 600)
        tgt = hm.enu_offset_to_lla(obs, e, n, u)
        enu = hm.lla_to_enu(obs, tgt)
        att = (random.uniform(0, 360), random.uniform(-30, 30), random.uniform(-30, 30))
        q = hm.q_from_euler(*att)
        p = hm.project(q, enu, cfg)
        cases.append({
            "obs": obs, "tgt": tgt, "enu": enu, "polar": hm.polar(enu),
            "att": att, "q": q, "proj": p,
        })

# Hand-checkable cases: target straight ahead / right / above with known attitude.
obs = OBS[0]
for name, (e, n, u), att in [
    ("north_ahead", (0, 1000, 0), (0, 0, 0)),
    ("east_ahead_when_facing_east", (1000, 0, 0), (90, 0, 0)),
    ("north_10deg_right", (1000 * hm.math.sin(hm.math.radians(10)), 1000 * hm.math.cos(hm.math.radians(10)), 0), (0, 0, 0)),
    ("behind", (0, -1000, 0), (0, 0, 0)),
]:
    tgt = hm.enu_offset_to_lla(obs, e, n, u)
    enu = hm.lla_to_enu(obs, tgt)
    q = hm.q_from_euler(*att)
    cases.append({"name": name, "obs": obs, "tgt": tgt, "enu": enu, "polar": hm.polar(enu),
                  "att": att, "q": q, "proj": hm.project(q, enu, cfg)})

with open(os.path.join(ROOT, "tests", "vectors.json"), "w") as f:
    json.dump({"cfg": {"width": cfg.width, "height": cfg.height, "hfov": cfg.hfov, "vfov": cfg.vfov},
               "cases": cases}, f, indent=1)

lines = [
    "/* Generated by tests/gen_vectors.py - do not edit. */",
    "#pragma once",
    "typedef struct { double obs[3], tgt[3], enu[3]; double bearing, elevation, range;",
    "  float att[3]; float q[4]; int in_front, on_screen; float sx, sy; } vec_case_t;",
    f"#define VEC_HFOV {cfg.hfov}f",
    f"#define VEC_VFOV {cfg.vfov}f",
    "static const vec_case_t VEC_CASES[] = {",
]
for c in cases:
    p = c["proj"]
    lines.append(
        "  {{%r,%r,%r},{%r,%r,%r},{%r,%r,%r},%r,%r,%r,{%rf,%rf,%rf},{%rf,%rf,%rf,%rf},%d,%d,%rf,%rf}," % (
            *c["obs"], *c["tgt"], *c["enu"], c["polar"]["bearing"], c["polar"]["elevation"], c["polar"]["range"],
            *[float(x) for x in c["att"]], *[float(x) for x in c["q"]], int(p["in_front"]), int(p["on_screen"]),
            float(p["sx"]), float(p["sy"])))
lines.append("};")
lines.append("#define VEC_COUNT (sizeof(VEC_CASES)/sizeof(VEC_CASES[0]))")
with open(os.path.join(ROOT, "firmware", "test_host", "vectors.h"), "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"wrote {len(cases)} cases")
