<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <OutputType>Library</OutputType>
    <RootNamespace>PrismHud.WinTAK</RootNamespace>
    <AssemblyName>PrismHud.WinTAK</AssemblyName>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.ComponentModel.Composition" />
    <Reference Include="System.Drawing" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Prism.Mef" Version="6.3.1" />
    <PackageReference Include="WinTak-Dependencies" Version="5.8.0.147" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\prism.svg" />
  </ItemGroup>
</Project>
